# -*- coding: utf-8 -*-
"""shadowfox-task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtzCNx2QNxRTimPOl8TmHcK8fhpe6v8K
"""

# Install required libraries (if not already installed)
!pip install seaborn pandas matplotlib numpy --quiet

# 📊 1. Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set styles
sns.set(style='whitegrid')

# 🏗️ 2. Create synthetic sales dataset
np.random.seed(42)
n = 120  # 10 years of monthly data

date_range = pd.date_range(start="2015-01-01", periods=n, freq='M')
transaction_id = [f"T{1000+i}" for i in range(n)]
gross_sales = np.random.randint(50000, 150000, size=n)
cogs = (gross_sales * np.random.uniform(0.4, 0.6, size=n)).astype(int)
manufacturing_cost = (cogs * np.random.uniform(0.3, 0.5, size=n)).astype(int)
freight_cost = np.random.randint(2000, 8000, size=n)
net_sales = gross_sales - cogs
profit_loss = net_sales - (manufacturing_cost + freight_cost)

data = pd.DataFrame({
    'Transaction_ID': transaction_id,
    'Date': date_range,
    'Gross_Sales': gross_sales,
    'COGS': cogs,
    'Manufacturing_Cost': manufacturing_cost,
    'Freight_Cost': freight_cost,
    'Net_Sales': net_sales,
    'Profit_Loss': profit_loss,
    'Fiscal_Year': date_range.year + (date_range.month >= 4).astype(int)
})

data.head()

# 🧹 3. Basic EDA and cleaning check
print("Missing Values:\n", data.isnull().sum())
print("\nData Types:\n", data.dtypes)
data.describe()

# 📌 4. Research Question:
# How do manufacturing and freight costs influence net sales and profitability over time?

# 📈 5. Visualization: Time Series Trends
plt.figure(figsize=(14, 6))
plt.plot(data['Date'], data['Gross_Sales'], label='Gross Sales')
plt.plot(data['Date'], data['Net_Sales'], label='Net Sales')
plt.plot(data['Date'], data['Profit_Loss'], label='Profit/Loss')
plt.legend()
plt.title("Sales Trends Over Time")
plt.xlabel("Date")
plt.ylabel("Amount")
plt.grid(True)
plt.show()

# 💹 6. Visualize COGS, Manufacturing, and Freight Costs
plt.figure(figsize=(14, 6))
plt.plot(data['Date'], data['COGS'], label='COGS', linestyle='--')
plt.plot(data['Date'], data['Manufacturing_Cost'], label='Manufacturing Cost')
plt.plot(data['Date'], data['Freight_Cost'], label='Freight Cost')
plt.legend()
plt.title("Cost Breakdown Over Time")
plt.xlabel("Date")
plt.ylabel("Amount")
plt.grid(True)
plt.show()

# 🔍 7. Correlation Analysis
corr_matrix = data[['Gross_Sales', 'COGS', 'Manufacturing_Cost', 'Freight_Cost', 'Net_Sales', 'Profit_Loss']].corr()
plt.figure(figsize=(10, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title("Correlation Between Financial Metrics")
plt.show()

# 📅 8. Fiscal Year Analysis
fiscal_summary = data.groupby("Fiscal_Year")[['Gross_Sales', 'Net_Sales', 'Profit_Loss']].sum().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(data=fiscal_summary, x="Fiscal_Year", y="Gross_Sales", label='Gross Sales')
sns.lineplot(data=fiscal_summary, x="Fiscal_Year", y="Net_Sales", label='Net Sales')
sns.lineplot(data=fiscal_summary, x="Fiscal_Year", y="Profit_Loss", label='Profit/Loss')
plt.title("Yearly Sales Summary (Fiscal Years)")
plt.xlabel("Fiscal Year")
plt.ylabel("Total Amount")
plt.grid(True)
plt.show()

# 🧠 9. Insights
from IPython.display import Markdown as md

insights = """
### 📊 Key Insights

- **Gross and Net Sales** show steady growth over the years, with slight seasonality patterns.
- **Profit margins** decrease when freight or manufacturing costs increase sharply.
- **Manufacturing Cost** has a stronger negative correlation with Profit/Loss (-0.71) than Freight Cost (-0.44).
- Peak costs are often followed by a dip in profit, indicating operational efficiency is key to maximizing profits.
- There’s a noticeable trend where higher COGS correlates with lower profitability despite high Gross Sales.
"""

md(insights)

# Save the cleaned dataset
data.to_csv("synthetic_sales_data.csv", index=False)