# -*- coding: utf-8 -*-
"""shadowfox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mWqn9hlek6uofjTanUqWsB9fPqYUgEjA
"""

import pandas as pd
df = pd.read_csv('/content/delhiaqi.csv')
df.head()

# Convert 'date' column to datetime
df['date'] = pd.to_datetime(df['date'])

# Create new time-related features
df['month'] = df['date'].dt.month
df['hour'] = df['date'].dt.hour
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.day_name()

# Assign seasons based on month
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Summer'
    elif month in [6, 7, 8]:
        return 'Monsoon'
    else:
        return 'Post-Monsoon'

df['season'] = df['month'].apply(get_season)
df.head()

# Categorize AQI levels from PM2.5 values using CPCB standards
def pm25_aqi(pm25):
    if pm25 <= 30:
        return 'Good'
    elif pm25 <= 60:
        return 'Satisfactory'
    elif pm25 <= 90:
        return 'Moderate'
    elif pm25 <= 120:
        return 'Poor'
    elif pm25 <= 250:
        return 'Very Poor'
    else:
        return 'Severe'

df['AQI_Category'] = df['pm2_5'].apply(pm25_aqi)
df[['date', 'pm2_5', 'AQI_Category']].head()

# Summary statistics
df.describe()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,5))
sns.lineplot(x='date', y='pm2_5', data=df, label='PM2.5')
sns.lineplot(x='date', y='pm10', data=df, label='PM10')
plt.title('PM2.5 & PM10 Trends Over Time')
plt.xlabel('Date')
plt.ylabel('Concentration (µg/m³)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(data=df, x='AQI_Category', order=['Good', 'Satisfactory', 'Moderate', 'Poor', 'Very Poor', 'Severe'], palette='coolwarm')
plt.title('AQI Category Distribution (Based on PM2.5)')
plt.ylabel('Number of Hours')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df, x='season', y='pm2_5', palette='Set2')
plt.title('Seasonal Variation of PM2.5')
plt.ylabel('PM2.5 (µg/m³)')
plt.xlabel('Season')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.drop(columns=['month', 'hour', 'day', 'weekday', 'season', 'date', 'AQI_Category']).corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Between Pollutants')
plt.tight_layout()
plt.show()